package it.marcodemartino.yapga.common.json;

public enum JSONMethods {

    REQUEST_IDENTITY_CERTIFICATE,
    ENCRYPTED_MESSAGE,
    REQUEST_REMOTE_PUBLIC_KEY,
    SEND_REMOTE_PUBLIC_KEY,
    SEND_IDENTITY_CERTIFICATE,
    SEND_IMAGE,
    REQUEST_IMAGES

}
